### ISSUE TITLE
Trying `npm start` fails with "By default, ts-loader will not compile .ts files in node_modules."

### ISSUE THREAD

**Issue by roa-nyx** [decentraland/builder#1443]
On Windows machine running `npm start` gives me the following:
```
> builder@2.17.1 start
> npm run build:scene && concurrently -n "scene,builder" "decentraland-compiler buildScene.json --watch" "npm run start:website"


> builder@2.17.1 build:scene
> decentraland-compiler buildScene.json

decentraland-compiler version: 3.1.8

      root: C:\****\src\ecsScene
    outDir: C:\****\src\ecsScene
   options: { coverage: false, production: true, watch: false }
     files:
            (root)/scene.ts -> (outDir)/scene.js
Build completed in 90.262s

Error: Hash: 91a3c7660b29b5db4d50
Version: webpack 4.44.1
Time: 90274ms
Built at: 06/12/2021 1:34:43 PM
   Asset     Size  Chunks  Chunk Names
scene.js  188 KiB       0  scene
Entrypoint scene = scene.js
[0] ./node_modules/decentraland-ecs/dist/src/index.js 158 KiB {0} [built]
[1] ./node_modules/tslib/tslib.es6.js 10.5 KiB {0} [built]
[2] ./src/ecsScene/scene.ts 17 KiB {0} [built]
[3] ./node_modules/events/events.js 13.3 KiB {0} [built]
[4] ./node_modules/decentraland-builder-scripts/channel.ts 772 bytes {0} [built] [failed] [1 error]
[5] ./node_modules/decentraland-builder-scripts/inventory.ts 774 bytes {0} [built] [failed] [1 error]
[6] ./src/modules/scene/types.ts 381 bytes {0} [built]
[7] ./src/modules/item/types.ts 4.13 KiB {0} [built]
[8] ./src/modules/editor/colors.ts 2.49 KiB {0} [built]
[9] ./node_modules/raw-loader!./src/ecsScene/amd-loader.js.raw 2.65 KiB {0} [built]

ERROR in ./node_modules/decentraland-builder-scripts/channel.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for C:\****\node_modules\decentraland-builder-scripts\channel.ts. By default, ts-loader will not compile .ts files in node_modules.
You should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.
See: https://github.com/Microsoft/TypeScript/issues/12358
    at makeSourceMapAndFinish (C:\****\node_modules\ts-loader\dist\index.js:80:15)
    at successLoader (C:\****\node_modules\ts-loader\dist\index.js:68:9)
    at Object.loader (C:\****\node_modules\ts-loader\dist\index.js:22:12)
 @ ./src/ecsScene/scene.ts 8:16-63

ERROR in ./node_modules/decentraland-builder-scripts/inventory.ts
Module build failed (from ./node_modules/ts-loader/index.js):
Error: TypeScript emitted no output for C:\****\node_modules\decentraland-builder-scripts\inventory.ts. By default, ts-loader will not compile .ts files in node_modules.
You should not need to recompile .ts files there, but if you really want to, use the allowTsInNodeModules option.
See: https://github.com/Microsoft/TypeScript/issues/12358
    at makeSourceMapAndFinish (C:\****\node_modules\ts-loader\dist\index.js:80:15)
    at successLoader (C:\****\node_modules\ts-loader\dist\index.js:68:9)
    at Object.loader (C:\****\node_modules\ts-loader\dist\index.js:22:12)
 @ ./src/ecsScene/scene.ts 9:18-67
    at C:\****\node_modules\decentraland-rpc\bin\compile.js:301:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\****\node_modules\decentraland-rpc\bin\compile.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Not sure how to diagnose or troubleshoot the issue. Any advice would be appreciated.

**Comment by cazala** [comment]
mm it says that you should turn on the `allowTsInNodeModules` option in your ts config. I don't have that option on and it works fine on my end tho, but maybe we are running different versions of typescript? I'm on `4.0.2`

**Comment by roa-nyx** [comment]
Not sure how to check @cazala. Wouldn't it be the typescript listed in the package.json? It shows:

```
    "typescript": "^4.0.2"
```

Is there something else I can check or post to help diagnose further? I'm currently installing Windows Subsystem for Linux, so I'll try to do it within a Linux context.

**Comment by LautaroPetaccio** [comment]
Closing it as there's a new build system in place.
