### ISSUE TITLE
[BUG] When speeding up a txn, the loading status never updates

### ISSUE THREAD

**Issue by cyaiox** [decentraland/builder#2604]
## 🎉 Description

* [x] 🐛 This is a bug report.
* [ ] 📈 This is a feature request.

## 📝 Details

When claiming a new name, if the network is slow and you speed up the txn, the UI keeps in a permanent loading status getting an error in the browser console:

```
TypeError: Cannot read properties of null (reading '_getInternalBlockNumber')
    at base-provider.ts:1417:21
    at Generator.next (<anonymous>)
    at 4.e5f597dd.chunk.js:8:3373250
    at new Promise (<anonymous>)
    at _ (4.e5f597dd.chunk.js:8:3372995)
    at getBlockNumber (4.e5f597dd.chunk.js:8:3391291)
    at M.<computed> (redux-saga-core.esm.js:524:21)
    at redux-saga-core.esm.js:1203:49
    at m (redux-saga-core.esm.js:1271:5)
    at p (redux-saga-core.esm.js:1161:9)
```

![image.png](https://images.zenhubusercontent.com/62b9d6aba5db8a6e9bb04b4c/8216c25c-66a5-411e-a989-539c3b7de44e)

## 🔢 Steps To Reproduce Issue [ Good To Have ]

Please remember that with baby steps it's easier to reproduce the bug and it's much faster to fix it.

```
- Step 1) Claim a new name
- Step 2) When processing txn, speed up
- Step 3) UI keeps in a permanent loading state
```

## 👍 Other Information
![image.png](https://images.zenhubusercontent.com/62b9d6aba5db8a6e9bb04b4c/7f58c233-5912-439b-bf8f-ce6ad884e18d)

**Comment by cyaiox** [comment]
Fixed in https://github.com/decentraland/builder/pull/2609
